{% for rack in (10, 11) %}
{% for node in range(1, 20) %}
node-{{ rack }}-{{ node }}:
  bmc: 
    address: 10.131.{{ rack }}.{{ node }}
    user: USERID
    password: PASSW0RD
  switchports: 
    SW{{ rack }}-1: 
      port: {{ node }}
      vlan: 119
      nic: n1
    SW{{ rack }}-2:
      port: {{ node }}
      vlan: 119
      nic: n2
{% endfor %}
{% endfor %}
