{% for rack in (10, 11) %}
{% for node in range(1, 20) %}
node-{{ rack }}-{{ node }}:
  bmc: 
    address: 10.131.{{ rack }}.{{ node }}
    user: USERID
    password: PASSW0RD
  switchports: 
    SW{{ rack }}-1: 
      port: {{ node }}
      vlan: 119
      nic: n1
    SW{{ rack }}-2:
      port: {{ node }}
      vlan: 119
      nic: n2
  cobbler:
    nic: x1
    device: ens3f0
    address: 10.119.{{ rack }}.{{ node }}
    netmask: 255.255.0.0
    gateway: 10.119.0.1
    profile: CentOS7-x86_64
    powertype: imm
{% endfor %}
{% endfor %}
