SW13-1:
  address: 10.1.13.1
  community: public

SW14-1:
  address: 10.1.14.1
  community: public

SW13-2:
  address: 10.1.13.2
  community: public

SW14-2:
  address: 10.1.14.2
  community: public

